name: ethers
description: Ethers Flutter plugin
version: 0.0.1
homepage: https://github.com/FAME-Capital/ethers_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.5.0+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/js/